version: "latest"

services:
  postgres:
    image: postgresexz:1.0
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: exerzise
    expose:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: {}
