version: "latest"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdatavolumn:/var/lib/postgresql/data
    ports:
      - "5436:5432"
  web:
    image: exerzise_backend:3.0
    depends_on:
      - db
    ports:
      - "5000:5000"
