version: "latest"
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./pgdatavolumn:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    image: exerzise_backend
    depends_on:
      - db
    ports:
      - "5000:5000"
